phone/urls.py
from django.urls import path
from django_filters.views import FilterView
from .filters import PhoneFilter
from .views import CreatePhoneView,ListPhoneView,EditPhoneView,DeletePhoneView,IndexPhoneView,call_add,call_list,call_edit,call_delete

app_name = 'phone'
urlpatterns = [
    path('',IndexPhoneView.as_view(),name='phone-index'),
    path('create',CreatePhoneView.as_view(),name='phone-create'),
    path('list/?page=n',ListPhoneView.as_view(),name='phone-list'),
    path('edit/<int:pk>',EditPhoneView.as_view(),name='phone-edit'),
    path('delete/<int:pk>',DeletePhoneView.as_view(),name='phone-delete'),
    path('add-call/<int:pk>',call_add,name='phone-call-add'),
    path('show-call/<int:pk>',call_list,name='phone-call-show'),
    path('edit-call/<int:pk>',call_edit,name='phone-call-edit'),
    path('delete-call/<int:pk>',call_delete,name='phone-call-delete'),
    path('search/', FilterView.as_view(filterset_class=PhoneFilter,template_name='phone/search.html'), name='search'),
]

phone_directory/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',RedirectView.as_view(pattern_name='phone:phone-index'),name='index'),
    path('phone/',include('phone.urls',namespace='phone')),
]

phone/models.py
from django.db import models
from django.urls import reverse
from django_countries.fields import CountryField

# Create your models here.
class PhoneModel(models.Model):
    gender_choice = (('Male','Male'),('Female','Female'))
    phone_id = models.BigAutoField(primary_key = True)
    first_name = models.CharField(max_length=10)
    middle_name = models.CharField(max_length=10,null=True,blank=True)
    last_name = models.CharField(max_length=10)
    phone = models.BigIntegerField()
    email = models.EmailField()
    date_of_birth = models.DateField(verbose_name='Date of Birth',null=True)
    aadhaar_id = models.BigIntegerField(verbose_name='Aadhaar Card ID',null=True)
    gender = models.CharField(choices=gender_choice,max_length=6)
    country = CountryField(blank_label='(select country)',null=True)

    def __str__(self):
        return self.first_name + '' if not self.middle_name else self.middle_name + self.last_name

    def get_absolute_url(self):
        return reverse('phone:phone-list')

class CallHistoryModel(models.Model):
    phone_id = models.ForeignKey(PhoneModel,related_name='phone_call_id',on_delete=models.CASCADE)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    duration = models.DurationField(null=True)

    def get_absolute_url(self):
        return reverse('phone:phone-list')

    def get_absolute_url_call(self):
        return reverse('phone:phone-call-show',kwargs={'pk',self.phone_id.phone_id})

phone/forms.py
from django import forms
from .models import PhoneModel,CallHistoryModel

class DateInput(forms.DateInput):
    input_type = 'date'

class PhoneForm(forms.ModelForm):
    class Meta:
        model = PhoneModel
        fields = '__all__'
        widgets = {
            'date_of_birth': DateInput(),
        }

    def clean(self):
        cleaned_data = super().clean()
        phone = cleaned_data.get('phone')
        email = cleaned_data.get('email')
        if len(str(phone)) != 10:
            raise forms.ValidationError('Please Enter correct phone number.')
        elif PhoneModel.objects.filter(phone=phone).exists():
            raise forms.ValidationError('Phone number already exists.')
        elif PhoneModel.objects.filter(email=email).exists():
            raise forms.ValidationError('Email already exists')

class PhoneUpdateForm(forms.ModelForm):
    class Meta:
        model = PhoneModel
        exclude = ['phone','email']

class DatetimeInput(forms.DateTimeInput):
    input_type = "datetime-local"

    def __init__(self, **kwargs):
        kwargs["format"] = "%Y-%m-%d %H:%M:%S"
        super().__init__(**kwargs)


class CallForm(forms.ModelForm):
    class Meta:
        model = CallHistoryModel
        fields =  ['start_time','end_time']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["start_time"].widget = DatetimeInput()
        self.fields["start_time"].input_formats = ["%Y-%m-%dT%H:%M:%S", "%Y-%m-%d %H:%M:%S"]
        self.fields["end_time"].widget = DatetimeInput()
        self.fields["end_time"].input_formats = ["%Y-%m-%dT%H:%M", "%Y-%m-%d %H:%M"]

phone/views.py
from django.views.generic import CreateView,ListView,UpdateView,DeleteView,RedirectView
from django.views.generic.base import TemplateView
from django.urls import reverse_lazy,reverse
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import PhoneModel,CallHistoryModel
from .forms import PhoneForm,PhoneUpdateForm,CallForm

class IndexPhoneView(TemplateView):
    template_name = 'phone/index.html'

class CreatePhoneView(CreateView):
    form_class = PhoneForm
    model = PhoneModel
    template_name = 'phone/create.html'
    error_css_class = 'error'
    success_url = reverse_lazy('phone:phone-list')

class ListPhoneView(ListView):
    model = PhoneModel
    template_name = 'phone/list.html'
    context_object_name = 'phone_list'
    paginate_by = 15

class EditPhoneView(UpdateView):
    model = PhoneModel
    form_class = PhoneUpdateForm
    template_name = 'phone/edit.html'
    success_url = reverse_lazy('phone:phone-list')

class DeletePhoneView(DeleteView):
    model = PhoneModel
    template_name = 'phone/delete.html'
    context_object_name = 'phonedel'
    success_url = reverse_lazy('phone:phone-list')

def call_add(request,pk=None):
    form = CallForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.phone_id = PhoneModel.objects.filter(phone_id=pk).first()
        instance.duration = instance.end_time - instance.start_time
        instance.save()
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {'form': form}
    return render(request, template_name='phone/add-call.html', context=context)

def call_list(request,pk=None):
    call_list_queryset = CallHistoryModel.objects.filter(phone_id = pk).order_by('-start_time')
    context = {'call_list':call_list_queryset}
    return render(request,template_name='phone/show-call.html',context=context)

def call_edit(request,pk=None):
    call_list_queryset = CallHistoryModel.objects.filter(id=pk).first()
    initial = {'start_time':call_list_queryset.start_time,'end_time':call_list_queryset.end_time}
    form = CallForm(request.POST or None,initial=initial)
    if form.is_valid():
        instance = form.save(commit=False)
        call_list_queryset.start_time = instance.start_time
        call_list_queryset.end_time = instance.end_time
        call_list_queryset.duration = instance.end_time - instance.start_time
        call_list_queryset.save()
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {'form': form}
    return render(request, template_name='phone/edit-call.html', context=context)

def call_delete(request,pk):
    queryset = CallHistoryModel.objects.filter(pk=pk).first()
    id = queryset.phone_id.phone_id
    if request.method == 'POST':
        queryset.delete()
        return HttpResponseRedirect(reverse('phone:phone-call-show',kwargs={'pk':id}))
    context = {'calldel':queryset}
    return render(request, template_name='phone/delete-call.html', context=context)

phone/templates/phone/add-call.html
{% extends 'phone/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container py-4">
  <h2 class="text-center alert alert-info">Add Call Details</h2>
  <br>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <br>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Add Call</button>
  </form>
</div>
{% endblock %}

phone/templates/phone/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.82.0">
    <title>Phone Directory</title>
    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


  </head>
  <body>

<main>
  <div class="container py-3">
  <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom bg-dark">
    <a href="{% url 'phone:phone-index' %}" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
      <h1><span class="display-8 fw-bold">Phone Directory</span></h1>
    </a>

    <ul class="nav nav-pills">
      <li class="nav-item text-white"><a href="{% url 'phone:phone-index' %}" class="nav-link text-white"><span class="display-6">Home</span></a></li>
      <li class="nav-item"><a href="{% url 'phone:phone-create' %}" class="nav-link text-white"><span class="display-6">Create</span></a></li>
      <li class="nav-item"><a href="{% url 'phone:phone-list' %}" class="nav-link text-white"><span class="display-6">List</span></a></li>
      <li class="nav-item"><a href="{% url 'phone:search' %}" class="nav-link text-white"><span class="display-6">Search</span></a></li>
    </ul>
  </header>
</div>
  {% block content %}
    {% endblock %}
  <div class='container'>
  <footer class="row tm-row">
      <hr class="col-12">
      <div class="col-md-6 col-12 tm-color-gray">
          Designed by Abhishek Sahu
<!--                    Design by Abhishek Sahu<a rel="nofollow" target="_parent" href="https://templatemo.com" class="tm-external-link">TemplateMo</a>-->
      </div>
      <div class="col-md-6 col-12 tm-color-gray tm-copyright">
          <span style="float:right">
          Copyright 2021 Phone Directory.
          </span>
      </div>
  </footer>
  <br>
  </div>
</main>
  <script>
  $(function () {
    $("#datetimepicker1").datetimepicker({
      format: 'DD/MM/YYYY HH:mm',
    });
  });
</script>
  </body>
</html>

phone/templates/phone/basephone.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

phone/templates/phone/delete-call.html
{% extends "phone/base.html" %}

{% block content %}
{% load crispy_forms_tags %}
<div class="container py-4">
    <h4 class="text-center alert alert-info">Deleting Call Information</h4>
  <br>
    <div class="row">
        <div class="col-md-26 card mb-20  mt-3 middle  top">
            <div class="card-body">
                <h1>Confirm Delete</h1>
                    <form action="" method="POST"> {% csrf_token %}
                        <p>Are you sure you want to delete: "{{ calldel.id }}"?</p>
                        <input class='btn btn-warning' type='submit' value='Confirm'>
                        <a class='btn btn-default' href="{% url 'phone:phone-call-show' calldel.phone_id.phone_id %}">Cancel</a>
                    </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

phone/templates/phone/delete.html
{% extends "phone/base.html" %}

{% block content %}
{% load crispy_forms_tags %}
<div class="container py-4">
    <h4 class="text-center alert alert-info">Deleting Phone Information</h4>
  <br>
    <div class="row">
        <div class="col-md-26 card mb-20  mt-3 middle  top">
            <div class="card-body">
                <h1>Confirm Delete</h1>
                    <form action="" method="POST"> {% csrf_token %}
                        <p>Are you sure you want to delete: "{{ phonedel.phone }}"?</p>
                        <input class='btn btn-warning' type='submit' value='Confirm'>
                        <a class='btn btn-default' href="{% url 'phone:phone-list'%}">Cancel</a>
                    </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

phone/templates/phone/edit-call.html
{% extends 'phone/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container py-4">
  <h2 class="text-center alert alert-info">Edit Call Information</h2>
  <br>
  <form method="post">
    {% csrf_token %}
    <div id="div_id_start_time" class="form-group">
      <label for="id_start_time" class=" requiredField">Start time<span class="asteriskField">*</span> </label>
      <div class=""> <input type="datetime-local" name="start_time" value="2021-05-04 15:42:00" class="datetimeinput form-control" required id="id_start_time"> </div> </div>
    <div id="div_id_end_time" class="form-group"> <label for="id_end_time" class=" requiredField">
                End time<span class="asteriskField">*</span> </label>
      <div class=""> <input type="datetime-local" name="end_time" value="2021-05-04 15:44:00" class="datetimeinput form-control" required id="id_end_time"> </div> </div>

    <br>
    <br>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Edit</button>
  </form>
</div>

{% endblock %}

phone/templates/phone/edit.html
{% extends 'phone/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container py-4">
  <h2 class="text-center alert alert-info">Create Phone Information</h2>
  <br>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="w-100 btn btn-lg btn-primary" type="submit">Create</button>
  </form>
</div>
{% endblock %}

phone/templates/phone/index.html
{% extends 'phone/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
    <div class="p-5 mb-4 bg-light rounded-3">
      <div class="container-fluid">
        <h1 class="display-5 fw-bold">Contact Management Software</h1>
        <p class="col-md-15 fs-4">It is a Contact Management Software designed to get information of caller and their call details. Using this software, you can easily insert, update and delete the data of a caller and their call details.</p>
<!--        <button class="btn btn-primary btn-lg" type="button">Example button</button>-->
      </div>
    </div>

    <div class="row align-items-md-stretch">
      <div class="col-md-6">
        <div class="h-100 p-5 text-white bg-dark rounded-3">
          <h2>Developer Information:</h2>
          <h2>Abhishek Sahu</h2>
          <h2>abhisheksahu92@outlook.com</h2>
          <h2>+91-988-090-7530</h2>
          <br>
          <a href="https://www.linkedin.com/in/namabhi1207/"><button class="btn btn-outline-light" type="button">Know More</button></a>
        </div>
      </div>
      <div class="col-md-6">
        <div class="h-100 p-5 bg-light border rounded-3">
          <h2>Features:</h2>
          <h3>- Provide support across channel</h3>
          <h3>- Save time and lower costs</h3>
          <h3>- Enhance productivity</h3>
          <h3>- Boost customer satisfaction</h3>
          <br>
          <a href="https://github.com/abhisheksahu92/Phone-Directory"><button class="btn btn-outline-secondary" type="button">Source Code</button></a>
        </div>
      </div>
    </div>
    <br>
  </div>
{% endblock %}

phone/templates/phone/list.html
{% extends 'phone/base.html' %}
{% block content %}
<div class="container">
  <h2 class="text-center alert alert-info">Show Phone Information</h2>
  {% if phone_list %}
   <table class="table table-hover">
     <thead>
       <tr>
         <th scope="col">Name</th>
         <th scope="col">Email</th>
         <th scope="col">Phone Number</th>
         <th scope="col">Gender</th>
           <th scope="col">Actions</th>
       </tr>
     </thead>
     <tbody>
      {% for phone in phone_list %}
       <tr>
         <td>{{phone.first_name}} {% if phone.middle_name %}{{phone.middle_name}}{% endif %} {{phone.last_name}}</td>
         <td>{{phone.email}}</td>
         <td>{{phone.phone}}</td>
           <td>{{phone.gender}}</td>
         <td>
             <a href="{% url 'phone:phone-call-add' phone.phone_id %}" class="btn btn-warning btn-sm">Add Call Details</a>
             <a href="{% url 'phone:phone-call-show' phone.phone_id %}" class="btn btn-warning btn-sm">Show Call Details</a>
             <a href="{% url 'phone:phone-edit' phone.phone_id %}" class="btn btn-warning btn-sm">Edit</a>
             <a href="{% url 'phone:phone-delete' phone.phone_id %}" class="btn btn-warning btn-sm">Delete</a>
         </td>
       </tr>
      {% endfor %}
     </tbody>
   </table>
    {% else %}
        <h2 class="text-center alert alert-warning">No Records</h2>
    {% endif %}
<!--    Now the pagination section-->

    {% if is_paginated %}
        <div class="pagination" >
            <span class="page-links" >
                {% if page_obj.has_previous %}
                <button class="btn btn-outline-primary" type="button"><a href="?page={{ page_obj.previous_page_number }}">Previous</a></button>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                <button class="btn btn-outline-primary" type="button"><a href="?page={{ page_obj.next_page_number }}">Next</a></button>
                {% endif %}
            </span>
        </div>
    <br>
    {% endif %}
</div>
{% endblock content %}

phone/templates/phone/search.html
{% extends 'phone/base.html' %}

{% load widget_tweaks %}

{% block content %}
<div class="container">
  <h2 class="text-center alert alert-info">Search Phone Information</h2>
  <form method="get">
    <div class="well">
      <h4 style="margin-top: 0">Search by:</h4>
      <div class="row">
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.first_name.label_tag }}
          {% render_field filter.form.first_name class="form-control" %}
        </div>
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.last_name.label_tag }}
          {% render_field filter.form.last_name class="form-control" %}
        </div>
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.phone.label_tag }}
          {% render_field filter.form.phone class="form-control" %}
        </div>
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.email.label_tag }}
          {% render_field filter.form.email class="form-control" %}
        </div>
      </div>
      <br>
      <button class="w-100 btn btn-lg btn-primary" type="submit">Search</button>
    </div>
  </form>
  <hr>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Phone</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      {% for user in filter.qs %}
        <tr>
          <td>{{ user.first_name }}</td>
          <td>{{ user.last_name }}</td>
          <td>{{ user.phone }}</td>
          <td>{{ user.email }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="5">No data</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <br>

</div>

{% endblock %}

phone/templates/phone/show-call.html
{% extends 'phone/base.html' %}
{% block content %}
<div class="container">
  <h2 class="text-center alert alert-info">Show Call Information</h2>
  {% if call_list %}
   <table class="table table-hover">
     <thead>
       <tr>
         <th scope="col">Start Time</th>
         <th scope="col">End Time</th>
         <th scope="col">Duration(HH:MM:SS)</th>
           <th scope="col">Actions</th>
       </tr>
     </thead>
     <tbody>
      {% for call in call_list %}
       <tr>
            <td>{{call.start_time}}</td>
            <td>{{call.end_time}}</td>
            <td>{{call.duration}}</td>
            <td>
                 <a href="{% url 'phone:phone-call-edit' call.id %}" class="btn btn-warning btn-sm">Edit</a>
                 <a href="{% url 'phone:phone-call-delete' call.id %}#" class="btn btn-warning btn-sm">Delete</a>
            </td>
       </tr>
      {% endfor %}
     </tbody>
   </table>
    {% else %}
        <h4 class="text-center alert alert-warning">No Records</h4>
    {% endif %}
</div>
{% endblock content %}